### PR TITLE
Limit react-bootstrap import to Input only

### PR DESCRIPTION
**Pull request by posgarou**
This PR reduces the impact of importing react-bootstrap and should reduce final file size for both this library and programs using it.  See http://react-bootstrap.github.io/getting-started.html#commonjs

### CODE REVIEW

**Comment by heilhead** [comment]
I'm actually reverting this for now as my tests showed that standalone build grows in size. Need to configure webpack properly for this to work.

**Comment by posgarou** [comment]
That's weird, thanks for letting me know. I'll try to have a look later
tonight as well.

**Comment by heilhead** [comment]
The problem is that react-bootstrap is marked as an external dependency in webpack config, but when you include 'react-bootstrap/lib/Input', it's not counted as external anymore. Also dragging another set of babel-runtime helpers with it...

Need to dig webpack configs to leave it as an external dependency to be able to use it with all kinds of loaders on frontend and not bundle it in.

Anyway, I'm not convinced that we'll be able to shrink the size of the build as it has no built-in react-bootstrap anyway.

**Comment by posgarou** [comment]
That makes sense, having looked at the config.

The problem comes when using react-bootstrap-validation in something else
built by webpack.  When I `import { Form, ValidatedInput} from
"react-bootstrap-validation";` in a test app, my webpack bundle size
increases by about 1/2 mb (uncompressed) due to importing all of
react-bootstrap.

Anyways, let me know whether you want to abandon the attempt or you want me
to have a go at modifying the external dependency setup to get the PR
mergeable.

**Comment by heilhead** [comment]
> When I `import { Form, ValidatedInput} from "react-bootstrap-validation";` in a test app, my webpack bundle size increases by about 1/2 mb (uncompressed) due to importing all of react-bootstrap.

If you're using only forms part of react-bootstrap, then this is a valid concern, but if you're already using react-bootstrap elsewhere in your project and adding react-bootstrap-validation blows out it's size a lot, this may be due to different versions used (i.e. 0.23 in react-bootstrap-validation and 0.22 in rest of your app).

Anyway, I'd appreciate if you dug deeper into webpack configuration and managed to make the lib require only Input class, as I don't really have much time lately to support and improve this library.

Thanks,
Ivan.

**Comment by posgarou** [comment]
I don't think it's a problem of different versions.  Adding `import
ReactBootstrap from "react-bootstrap"` after importing
`react-bootstrap-validation` doesn't change the bundle size.

I'll definitely dig deeper and get back to you.

Thanks for the work on the library, by the way—I think React is lacking in
form validation libraries, so this is a great addition to the React
ecosystem.

**Pull request merged**
