### PR TITLE
Support React 15.2.0. Update Babel dependencies.

### LINKED ISSUE #65: Input bootstrap element is deprecated
`<Input>` has been deprecated in favour of `<FormControl>`

ValidatedInput should be using FormControl.

### LINKED ISSUE #66: React 15.2.0 Warnings: Unknown props
In React 15.2.0, props that aren't explicitly defined on the propTypes object should not be used. If you do, you get a warning. Because of this, ValidatedInput should strip off the props it needs and only forward the rest to the inherited react-bootstrap control.

### PR DESCRIPTION
**Pull request by plemarquand**
Fixes #65
Fixes #66

### CODE REVIEW

**Comment by camsjams** [comment]
+1

**Comment by basilfx** [comment]
This version seems to work with react-bootstrap 0.30.0.

**Comment by camsjams** [comment]
@basilfx Agreed!

If you look at [version 0.30.0](https://github.com/react-bootstrap/react-bootstrap/tree/v0.30.0/src) of React Bootstrap, there is no component named `Input`, but in React Bootstrap Validation `v0.1.11` for the `ValidatedInput` component, there is a reference to the [Input component](https://github.com/heilhead/react-bootstrap-validation/blob/master/src/ValidatedInput.js#L2), which leads to an error: `super expression must be null or a function`

**Comment by basilfx** [comment]
@camsjams But this PR doesn't use Input, but [FormControl](https://github.com/plemarquand/react-bootstrap-validation/blob/4cef4dfe05859e1cb4649f8865308e1b29bcf605/src/ValidatedInput.js). Your link references to the source of this repository, not the source of this PR.

I found that it renders fine, but I have some other problems using value links right now.

**Comment by camsjams** [comment]
Ah sorry, misunderstood your original comment. We are in agreement 👍

**Comment by ghost** [comment]
@plemarquand Wouldn't it make more sense if the `ValidatedInput` component was called `ValidatedFormGroup` (or similar) since it renders a `FormGroup`, not a `FormControl`?

**Comment by ir-fuel** [comment]
Can this be merged please? There is no way of using this lib with React 15 right now as I get the "Uncaught TypeError: Super expression must either be null or a function, not undefined" on usage of ValidatedInput in my project :(

**Comment by ir-fuel** [comment]
Upon taking a closer look, this isn't a plugin replacement for the old version. In the older versions of `react-bootstrap` the `Input` component both had a label and a text field. So did the `ValidatedInput` component. In this new version only the text field has been taken into account, not the previously supported label, so basically this breaks the old behaviour of the component.

**Comment by ghost** [comment]
@ir-fuel For me it still works fine in React 15. If I understand correctly, this is meant to be used as a replacement to `react-bootstrap`'s new `FormControl`. You would put your own `FormGroup` and `ControlLabel`around it, which is why no `label` prop is needed.

**Comment by LoicUV** [comment]
@gchameleon except if you need to specify the validationState on the FormGroup for styling purposes which is a react-bootstrap standard now, you can't. Or any other implementation that relied on using label now doesn't work as @ir-fuel stated.

**Comment by nguyenbathanh** [comment]
I couldn't make this work. The errors are not showing in form.

**Comment by amariani** [comment]
@plemarquand Hi and thanks for the fix! How can I install your version in my project? I tried to npm install it  running `npm i -S plemarquand/react-bootstrap-validation` but then I realized  it doesn't include the dist folder so I can not use it. Is there a way I can fork your repo and build the package so I can use it? Thanks in advance!

**Pull request closed without merging**
