### PR TITLE
Alter Form and ValidatedInput to bind through context

### PR DESCRIPTION
**Pull request by impleri**
A shallow, likely WIP attempt at resolving #8. Mirrors a lot of what react-router-bootstrap does. ValidatedInput is now a wrapper that should contain a single Input.

### CODE REVIEW

**Comment by impleri** [comment]
Had to rework the solution so it'd work in practice. One benefit is that it'll keep the same usage as the current implementation (i.e. no need to wrap an Input within the ValidatedInput).

**Comment by impleri** [comment]
OK, this is certainly ready for review. I've tested with every input type, some deeply nested and provided by other components.

**Comment by heilhead** [comment]
Thanks for your contribution! I'll take a closer look next week.

**Comment by impleri** [comment]
Closing this in favor of a different implementation.

**Pull request closed without merging**
